export const educationalItems: string[] = [
    "Waffle maker",
    "Periodic table",
    "Microscope",
    "Textbook",
    "Whiteboard",
    "Graphing calculator",
    "Flashcards",
    "Globes",
    "Skeleton model",
    "Volcano kit",
    "Art supplies",
    "Science lab equipment",
    "Mathematical instruments",
    "Educational games",
    "Coding robot",
    "Virtual reality headset",
    "Puzzle pieces",
    "Learning apps",
    "Smartboard",
    "Abacus",
    "Chemistry set",
    "Planetarium projector",
    "Ruler",
    "Compasses",
    "Geometric shapes",
    "Osmosis kit",
    "Astronomy telescope",
    "Educational software",
    "Math manipulative kit",
    "Historical artifacts",
    "DNA model",
    "Solar system model",
    "Biology charts",
    "Interactive globe",
    "Robotics kit",
    "Language learning app",
    "E-books",
    "Simulation software",
    "Physics lab kit",
    "Educational posters",
    "Coding books",
    "Science experiment kits",
    "Digital microscope",
    "3D printer",
    "Math puzzles",
    "Science magazines",
    "Cameras for projects",
    "Environmental science kit",
    "Programming courses",
    "Engineering kits",
    "Interactive whiteboard",
    "Math games",
    "Science documentaries",
    "Geography maps",
    "History books",
    "Music theory books",
    "Art kits",
    "Drawing tablets",
    "Robotic arms",
    "Solar panel kits",
    "Science field guides",
    "Virtual labs",
    "Cultural artifacts",
    "Mathematical software",
    "Foreign language dictionaries",
    "Educational YouTube channels",
    "Science experiment videos",
    "Robotics kits",
    "Microspheres",
    "Genetics kits",
    "Computer science textbooks",
    "Statistics software",
    "Biology lab tools",
    "Physics textbooks",
    "Language learning games",
    "Interactive simulations",
    "Historical documentaries",
    "Mathematical games",
    "Chemistry models",
    "Physics experiment kits",
    "Engineering textbooks",
    "Astronomy books",
    "Geological maps",
    "Art and design software",
    "Music instruments",
    "Chemistry lab equipment",
    "Physics lab apparatus",
    "Biology field guides",
    "Environmental science resources",
    "Educational apps for kids",
    "Online course subscriptions",
    "Virtual reality learning experiences",
    "Artificial intelligence kits",
    "Smart learning devices",
    "Interactive learning platforms",
    "Educational podcasts",
    "Interactive science kits",
    "Language learning software",
    "Creative writing prompts",
    "Physics simulation tools",
    "Chemistry experiment guides",
    "Engineering design software",
    "Educational mobile apps",
    "Science project kits",
    "Mathematics workbooks",
    "Geography field guides",
    "Astronomy software",
    "Coding bootcamps",
    "Interactive math apps",
    "3D modeling software",
    "Science trivia games",
    "Mathematics puzzles",
    "Environmental science textbooks",
    "Historical simulations",
    "Physics online courses",
    "Music composition software",
    "Chemistry online resources",
    "Biology simulation tools",
    "Language learning games for kids",
    "Engineering project kits",
    "Astronomy observation tools",
    "Virtual lab simulations",
    "Math manipulation tools",
    "Science experiment kits for kids",
    "Programming challenge platforms",
    "Mathematical logic puzzles",
    "Geological tools",
    "Robotics challenge kits",
    "Science fiction books",
    "History documentaries for kids",
    "Biology educational kits",
    "Chemistry for beginners kits",
    "Physics educational apps",
    "Mathematics exploration kits",
    "Astronomy observation kits",
    "Computer programming tutorials",
    "Engineering design projects",
    "Music theory apps",
    "Interactive science textbooks",
    "Virtual science labs",
    "Educational game consoles",
    "Geography exploration kits",
    "Digital drawing tools",
    "Mathematics problem-solving kits",
    "Science project ideas",
    "Chemistry lab guides",
    "Physics problem sets",
    "Biology experiment tools",
    "Astronomy learning resources",
    "Engineering activity kits",
    "Robotics programming tools",
    "Educational board games",
    "Math learning resources",
    "Science fiction movies",
    "History exploration kits",
    "Language arts workbooks",
    "Creative arts supplies",
    "Physics experiment guides",
    "Chemistry educational games",
    "Mathematics instructional videos",
    "Biology fieldwork guides",
    "Astronomy educational apps",
    "Engineering hands-on activities",
    "Music education resources",
    "Science educational kits",
    "Mathematics tutoring platforms",
    "Interactive educational websites",
    "Virtual reality science kits",
    "Historical artifact replicas",
    "Physics lab guides",
    "Math visualization tools",
    "Science trivia apps",
    "Chemistry project kits",
    "Biology study guides",
    "Engineering simulation tools",
    "Astronomy learning kits",
    "Language development apps",
    "Educational TV shows",
    "Creative writing software",
    "Mathematics educational toys",
    "Physics activity kits",
    "Biology learning resources",
    "Chemistry interactive lessons",
    "Science experiment resources",
    "Engineering project plans",
    "Astronomy observation guides",
    "Educational workshops",
    "Math challenge books",
    "Physics lab notebooks",
    "Biology educational videos",
    "Chemistry research tools",
    "Engineering educational apps",
    "Science educational magazines",
    "Mathematics activity sheets",
    "Robotics learning resources",
    "Interactive learning games",
    "Virtual reality educational games",
    "History simulation tools",
    "Geography exploration activities",
    "Science project management tools",
    "Mathematics digital resources",
    "Physics study aids",
    "Biology lab experiments",
    "Chemistry interactive apps",
    "Engineering innovation kits",
    "Astronomy learning kits for kids",
    "Mathematics problem sets for kids",
    "Science curriculum guides",
    "Physics educational materials",
    "Biology exploration kits",
    "Chemistry research kits",
    "Engineering problem-solving tools",
    "Astronomy observation resources",
    "Interactive educational software",
    "Robotics learning kits",
    "Educational video games",
    "Mathematics learning kits",
    "Physics simulation tools for kids",
    "Biology interactive lessons",
    "Chemistry educational videos",
    "Engineering learning resources",
    "Astronomy educational kits for kids",
    "Science learning activities",
    "Mathematics games for kids",
    "Engineering design kits",
    "Physics interactive lessons",
    "Biology educational software",
    "Chemistry lab notebooks",
    "Mathematics online courses",
    "Science teaching aids",
    "Robotics kits for beginners",
    "Astronomy educational games",
    "Creative writing activities",
    "Physics teaching resources",
    "Biology field kits",
    "Chemistry interactive kits",
    "Mathematics educational guides",
    "Engineering educational videos",
    "Science kit subscriptions",
    "Educational comic books",
    "Mathematics activity books",
    "Physics research kits",
    "Biology exploration tools",
    "Chemistry learning resources",
    "Engineering challenge platforms",
    "Astronomy observation apps",
    "Mathematics virtual labs",
    "Science kits for kids",
    "Robotics simulation software",
    "Educational curriculum software",
    "Biology teaching aids",
    "Physics experiment plans",
    "Chemistry educational guides",
    "Mathematics study aids",
    "Engineering project tutorials",
    "Astronomy interactive apps",
    "Science game apps",
    "Educational simulation kits",
    "Robotics learning platforms",
    "Physics virtual labs",
    "Biology activity kits",
    "Chemistry educational materials",
    "Mathematics research tools",
    "Engineering simulation resources",
    "Astronomy educational platforms",
    "Science teaching materials",
    "Robotics educational kits",
    "Mathematics problem books",
    "Physics exploration kits",
    "Biology educational kits for kids",
    "Chemistry interactive resources",
    "Engineering challenge kits",
    "Astronomy educational materials",
    "Science curriculum materials",
    "Robotics educational platforms",
    "Mathematics learning apps",
    "Physics study resources",
    "Biology educational videos",
    "Chemistry hands-on kits",
    "Engineering instructional videos",
    "Astronomy observation guides",
    "Science educational websites",
    "Robotics simulation tools",
    "Mathematics virtual resources",
    "Physics activity resources",
    "Biology educational software for kids",
    "Chemistry research resources",
    "Engineering interactive apps",
    "Astronomy educational guides",
    "Science learning kits for kids",
    "Robotics learning resources for kids",
    "Mathematics teaching tools",
    "Physics experiment resources",
    "Biology exploration resources",
    "Chemistry interactive learning",
    "Engineering design tools",
    "Astronomy study aids",
    "Science educational kits for kids",
    "Robotics educational resources",
    "Mathematics challenge kits",
    "Physics educational materials for kids",
    "Biology interactive kits",
    "Chemistry curriculum guides",
    "Engineering educational software",
    "Astronomy learning resources for kids",
    "Science activity guides",
    "Robotics programming resources",
    "Mathematics learning tools",
    "Physics teaching resources for kids",
    "Biology lab kits",
    "Chemistry interactive activities",
    "Engineering problem-solving kits",
    "Astronomy educational kits for students",
    "Science project resources",
    "Robotics educational apps",
    "Mathematics exploration tools",
    "Physics study guides for kids",
    "Biology research tools",
    "Chemistry hands-on activities",
    "Engineering challenge resources",
    "Astronomy observation kits for kids",
    "Science teaching aids for kids",
    "Robotics learning guides",
    "Mathematics study materials",
    "Physics interactive kits",
    "Biology learning tools",
    "Chemistry educational activities",
    "Engineering resources for kids",
    "Astronomy interactive guides",
    "Science educational kits for students",
    "Robotics teaching resources",
    "Mathematics problem-solving tools for kids",
    "Physics experiment guides for kids",
    "Biology educational materials",
    "Chemistry virtual labs",
    "Engineering instructional materials",
    "Astronomy educational resources for kids",
    "Science project ideas for students",
    "Robotics challenge kits for kids",
    "Mathematics learning guides",
    "Physics curriculum resources",
    "Biology interactive resources for kids",
    "Chemistry educational kits for students",
    "Engineering learning resources for kids",
    "Astronomy study materials for students",
    "Science teaching tools for kids",
    "Robotics instructional materials",
    "Mathematics virtual resources for kids",
    "Physics research guides",
    "Biology learning kits for students",
    "Chemistry hands-on learning",
    "Engineering activity kits for kids",
    "Astronomy educational videos",
    "Science learning apps for students",
    "Robotics learning tools for kids",
    "Mathematics teaching guides",
    "Physics study materials for students",
    "Biology interactive educational kits",
    "Chemistry curriculum materials for kids",
    "Engineering teaching resources for kids",
    "Astronomy learning activities",
    "Science project management tools for students",
    "Robotics educational materials for kids",
    "Mathematics exploration kits for students",
    "Physics learning guides for kids",
    "Biology research kits for students",
    "Chemistry interactive educational tools",
    "Engineering educational kits for students",
    "Astronomy interactive learning tools",
    "Science teaching aids for students",
    "Robotics problem-solving resources",
    "Mathematics learning resources for kids",
    "Physics educational guides for students",
    "Biology exploration kits for students",
    "Chemistry virtual resources",
    "Engineering instructional resources for kids",
    "Astronomy educational tools",
    "Science activity materials for students",
    "Robotics educational games",
    "Mathematics virtual labs for kids",
    "Physics problem-solving guides",
    "Biology educational guides for students",
    "Chemistry hands-on resources",
    "Engineering activity resources for kids",
    "Astronomy study guides for students",
    "Science teaching guides for kids",
    "Robotics learning materials for students",
    "Mathematics exploration resources for kids",
    "Physics research kits for students",
    "Biology interactive learning resources",
    "Chemistry educational activities for kids",
    "Engineering challenge tools for students",
    "Astronomy interactive materials",
    "Science educational apps for students",
    "Robotics instructional resources for kids",
    "Mathematics problem-solving resources for students",
    "Physics virtual resources for kids",
    "Biology lab guides for students",
    "Chemistry curriculum guides for students",
    "Engineering educational tools for kids",
    "Astronomy learning guides for students",
    "Science project kits for students",
    "Robotics challenge resources for kids"
];
