/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/OxLoykJwGxB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover"
import { Button } from "@/components/ui/button"
import { JSX, SVGProps } from "react"
import { Grid2X2, Pencil, Sparkles, Terminal } from "lucide-react"
import { Badge } from "../ui/badge"
import GallerySection from "../apps/GallerySection"

export default function AppsPopup(
  {
    submit
  }: {
    submit: Function
  }
) {
  return (
    <Popover>
      <PopoverTrigger asChild>
        <Button className="!bg-transparent p-0  relative mr-5">
          <Grid2X2 className="hover:animate-pulse text-gray-600" />
        </Button>

      </PopoverTrigger>
      <PopoverContent className="w-[300px] grid grid-cols-3 gap-4 p-4 rounded-3xl">
        <GallerySection submit={submit} />
        <div className="flex flex-col items-center gap-2 relative text-gray-500 cursor-not-allowed">
          <Sparkles className="w-6 h-6" />
          <span className="text-sm font-medium">Suggestions</span>
          <span className="text-xs text-gray-500">Coming Soon</span> {/* Added "Coming Soon" text */}
        </div>
        <div className="flex flex-col items-center gap-2 relative text-gray-500 cursor-not-allowed">
          <RewindIcon className="w-6 h-6" />
          <span className="text-sm font-medium">Rebuttal</span>
          <span className="text-xs text-gray-500">Coming Soon</span> {/* Added "Coming Soon" text */}
        </div>
        <div className="flex flex-col items-center gap-2 relative text-gray-500 cursor-not-allowed">
          <Pencil className="w-6 h-6" />
          <span className="text-sm font-medium">Rewrite</span>
          <span className="text-xs text-gray-500">Coming Soon</span> {/* Added "Coming Soon" text */}
        </div>
        <div className="flex flex-col items-center gap-2 relative text-gray-500 cursor-not-allowed">
          <Terminal className="w-6 h-6" />
          <span className="text-sm font-medium">Prompt</span>
          <span className="text-xs text-gray-500">Coming Soon</span> {/* Added "Coming Soon" text */}
        </div>
      </PopoverContent>


    </Popover>
  )
}

function BookmarkIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z" />
    </svg>
  )
}


function BriefcaseIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>
  )
}


function CalendarIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function ImageIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <circle cx="9" cy="9" r="2" />
      <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
    </svg>
  )
}


function RewindIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="11 19 2 12 11 5 11 19" />
      <polygon points="22 19 13 12 22 5 22 19" />
    </svg>
  )
}


function WebcamIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="10" r="8" />
      <circle cx="12" cy="10" r="3" />
      <path d="M7 22h10" />
      <path d="M12 22v-4" />
    </svg>
  )
}
