/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ScjVsaJpOZK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import Image from "next/image"

export default function ActualGallery() {
  const products = [
    {
      id: 1,
      image: "/placeholder.svg",
      title: "Wireless Earbuds",
      description: "Experience crystal clear audio on the go.",
    },
    {
      id: 2,
      image: "/placeholder.svg",
      title: "Ergonomic Desk Chair",
      description: "Improve your posture and comfort while working.",
    },
    {
      id: 3,
      image: "/placeholder.svg",
      title: "Smart Home Hub",
      description: "Control your connected devices with ease.",
    },
    {
      id: 4,
      image: "/placeholder.svg",
      title: "Portable Bluetooth Speaker",
      description: "Bring the party wherever you go.",
    },
    {
      id: 5,
      image: "/placeholder.svg",
      title: "Fitness Tracker",
      description: "Monitor your activity and health metrics.",
    },
    {
      id: 6,
      image: "/placeholder.svg",
      title: "Noise-Cancelling Headphones",
      description: "Immerse yourself in your music or podcasts.",
    },
  ]
  return (
    <section className="grid gap-6 md:grid-cols-2 lg:grid-cols-3 px-4 md:px-6 py-12">
      {products.map((product) => (
        <div key={product.id} className="flex flex-col md:flex-row bg-background rounded-lg shadow-lg overflow-hidden">
          <Image
            src="/logo.png"
            alt={product.title}
            width={400}
            height={400}
            className="md:w-1/2 object-cover"
            style={{ aspectRatio: "400/400", objectFit: "cover" }}
          />
          <div className="flex-1 p-6 md:p-8 flex flex-col justify-between max-w-[70%]">
            <div>
              <h3 className="text-xl font-bold">{product.title}</h3>
              <p className="text-muted-foreground mt-2">{product.description}</p>
            </div>
            <Button size="sm" className="mt-6">
              Create Curriculum
            </Button>
          </div>
        </div>
      ))}
    </section>
  )
}
