/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ScjVsaJpOZK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import Image from "next/image"
import { GalleryItems, Item } from "@/lib/galleryItems"
import { TriangleAlertIcon, Ellipsis, ListIcon, FilePenIcon } from "lucide-react"
import {
  Popover,
  PopoverTrigger,
  PopoverContent
} from "../ui/popover"
import { Switch } from "../ui/switch"
import CreateByComponent from "./CreateByComponent"

export default function ActualGallery({
  searchQuery,
  selectedSubject,
  input
}: {
  searchQuery: string,
  selectedSubject: string,
  input: string
}) {

  const check = (val: Item) => {
    return searchQuery === "" || val.name.toLowerCase().indexOf(searchQuery.toLowerCase()) !== -1;
  }

  return (
    <section className="grid gap-6 md:grid-cols-2 px-4 md:px-6 py-12">
      {
        GalleryItems.filter((val) => check(val)).length > 0 ? <>
          {GalleryItems.filter(
            (val) => check(val)
          ).map((product, index) => (
            <CreateByComponent
               key={index} 
               product={product}
               searchQuery={searchQuery}
               selectedSubject={selectedSubject}
               input={input}
              />
          ))}
        </> : <>
          <div className="w-[82vw] grid place-items-center text-center mx-auto">
            <TriangleAlertIcon className="mx-auto h-12 w-12 text-primary" />
            <h1 className="mt-4 text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
              Sorry, we couldn{"'"}t find what you were looking for.
            </h1>
            <p className="mt-4 text-muted-foreground">
              The content you requested could not be found. Please check your search query and try again.
            </p>
          </div>
        </>
      }
    </section>
  )
}
