import { GalleryHorizontalEnd } from "lucide-react";
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog"
import { Badge } from "../ui/badge";
import ActualGallery from "../component/gallery-section";
import { ScrollArea } from "../ui/scroll-area";


export default function GallerySection() {
    return <>
        <Dialog>
            <DialogTrigger>
                <div className="flex flex-col items-center gap-2">
                    <GalleryHorizontalEnd className="w-6 h-6" />
                    <span className="text-sm font-medium">Gallery</span>
                    <Badge variant={"destructive"}>New</Badge>
                </div>
            </DialogTrigger>
            <DialogContent className="w-[95vw] lg:w-[90vw]">
                <DialogHeader>
                    <DialogTitle>Gallery</DialogTitle>
                    <DialogDescription>
                        A scroll page where you explore products and generate a custom curriculum based on what piques your interest. All images are generated by Meta AI.
                    </DialogDescription>
                </DialogHeader>
                <ScrollArea className="max-h-[76vh]">
                    <ActualGallery/>
                </ScrollArea>
            </DialogContent>
        </Dialog>
    </>
}