"use client"

import { GalleryHorizontalEnd, SearchIcon, SlidersHorizontal, Target } from "lucide-react";
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog"
import { Badge } from "../ui/badge";
import ActualGallery from "../component/gallery-section";
import { ScrollArea } from "../ui/scroll-area";
import { Input } from "@/components/ui/input"
import { useState } from "react";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/components/ui/select"
import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
} from "@/components/ui/accordion"


export default function GallerySection() {

    const [searchQuery, setSearchQuery] = useState("")
    const [selectedSubject, setSelectedSubject] = useState("")
    const [input, setInput] = useState("");

    return <>
        <Dialog>
            <DialogTrigger>
                <div className="flex flex-col items-center gap-2">
                    <GalleryHorizontalEnd className="w-6 h-6" />
                    <span className="text-sm font-medium">Gallery</span>
                    <Badge variant={"destructive"}>New</Badge>
                </div>
            </DialogTrigger>
            <DialogContent className="w-[95vw] lg:w-[90vw] rounded-2xl">
                <DialogHeader>
                    <DialogTitle>Gallery</DialogTitle>
                    <DialogDescription className="flex flex-col">
                        A scroll page where you explore products and generate a custom curriculum based on what piques your interest. All images are generated by Meta AI.
                        <Accordion type="single" collapsible className="w-[96%] mx-auto">
                            <AccordionItem value="item-1">
                                <AccordionTrigger >Filtering Options</AccordionTrigger>
                                <AccordionContent className="w-[96%] mx-auto flex flex-col lg:flex-row gap-3 mt-2 justify-between">

                                    <div className="relative w-full lg:w-1/3">
                                        <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                                        <Input
                                            type="search"
                                            placeholder="Search products..."
                                            value={searchQuery}
                                            onChange={(e) => setSearchQuery(e.target.value)}
                                            className="w-full rounded-lg bg-background pl-8 pr-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent"
                                        />
                                    </div>
                                    <div className="relative w-full lg:w-2/3 flex gap-3 flex-row">
                                        <div className="relative w-full ">
                                            <SlidersHorizontal className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                                            <Select onValueChange={
                                                (value) => {
                                                    setSelectedSubject(value);
                                                }
                                            }>
                                                <SelectTrigger className="pl-10 w-full">
                                                    <SelectValue placeholder={selectedSubject == "" ? "Subject" : selectedSubject} />
                                                </SelectTrigger>
                                                <ScrollArea className="max-h-[300px]">
                                                    <SelectContent className="max-h-[300px]">
                                                        <SelectTitle>Core Subjects</SelectTitle>
                                                        <SelectItem value="Math">Math</SelectItem>
                                                        <SelectItem value="Science">Science</SelectItem>
                                                        <SelectItem value="History">History</SelectItem>
                                                        <SelectTitle>World Language</SelectTitle>
                                                        <SelectItem value="English">English</SelectItem>
                                                        <SelectItem value="Spanish">Spanish</SelectItem>
                                                        <SelectItem value="Mandarin">Mandarin</SelectItem>
                                                        <SelectItem value="Hindi">Hindi</SelectItem>
                                                        <SelectItem value="Arabic">Arabic</SelectItem>
                                                        <SelectItem value="Portuguese">Portuguese</SelectItem>
                                                        <SelectItem value="German">German</SelectItem>
                                                        <SelectItem value="French">French</SelectItem>
                                                        <SelectItem value="Italian">Italian</SelectItem>
                                                        <SelectItem value="Korean">Korean</SelectItem>
                                                        <SelectItem value="World Language">World Language</SelectItem>
                                                        <SelectTitle>Computer Science</SelectTitle>
                                                        <SelectItem value="Computer Science">Computer Science</SelectItem>
                                                    </SelectContent>
                                                </ScrollArea>
                                            </Select>
                                        </div>
                                        <div className="relative w-full">
                                            <Target className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                                            <Input
                                                type="search"
                                                placeholder="Title"
                                                value={input}
                                                onChange={(e) => setInput(e.target.value)}
                                                className="w-full rounded-lg bg-background pl-8 pr-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent"
                                            />

                                        </div>
                                    </div>

                                </AccordionContent>
                            </AccordionItem>
                        </Accordion>


                    </DialogDescription>
                </DialogHeader>
                <ScrollArea className="max-h-[50vh] lg:max-h-[55vh]">
                    <ActualGallery searchQuery={searchQuery} selectedSubject={selectedSubject} input={input} />
                </ScrollArea>
            </DialogContent>
        </Dialog>
    </>
}

function SelectTitle(
    {
        children
    }: {
        children: any
    }
) {
    return <>
        <h1 className="ml-3 text-sm text-gray-900 my-2 font-semibold">{children}</h1>
    </>
}