"use client"

import { GalleryHorizontalEnd, SearchIcon, SlidersHorizontal, Target } from "lucide-react";
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog"
import { Badge } from "../ui/badge";
import ActualGallery from "../component/gallery-section";
import { ScrollArea } from "../ui/scroll-area";
import { Input } from "@/components/ui/input"
import { useState } from "react";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/components/ui/select"
import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
} from "@/components/ui/accordion"
import { Button } from "../ui/button";
import Link from "next/link";


export default function GallerySection() {

    const [searchQuery, setSearchQuery] = useState("")
    const [selectedSubject, setSelectedSubject] = useState("")
    const [input, setInput] = useState("");

    return <>
        <Dialog>
            <DialogTrigger>
                <div className="flex flex-col items-center gap-2">
                    <GalleryHorizontalEnd className="w-6 h-6" />
                    <span className="text-sm font-medium">Gallery</span>
                    <Badge variant={"destructive"}>New</Badge>
                </div>
            </DialogTrigger>
            <DialogContent className="w-[95vw] lg:w-[90vw] rounded-2xl">
                <DialogHeader>
                    <DialogTitle>Gallery</DialogTitle>
                    <DialogDescription className="flex flex-row gap-2">
                        <>A scroll page where you explore products and generate a custom curriculum based on what piques your interest. All images are generated by Meta AI. <Link href={"https://forms.gle/TKgtnAL6qjtYAQLGA"} className="text-blue-400 font-semibold">Recommendation Form</Link></>
                    </DialogDescription>
                    <Accordion type="single" collapsible className="w-[96%] mx-auto" defaultValue="item-1">
                        <AccordionItem value="item-1">
                            <AccordionTrigger >Filtering Options</AccordionTrigger>
                            <AccordionContent className="w-[96%] mx-auto flex flex-col lg:flex-row gap-3 mt-2 justify-between">

                                <div className="relative w-full lg:w-1/3">
                                    <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                                    <Input
                                        type="search"
                                        placeholder="Search products..."
                                        value={searchQuery}
                                        onChange={(e) => setSearchQuery(e.target.value)}
                                        className="w-full rounded-lg bg-background pl-8 pr-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent"
                                    />
                                </div>
                                <div className="relative w-full lg:w-2/3 flex gap-3 flex-row">
                                    <div className="relative w-full ">
                                        <SlidersHorizontal className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                                        <Select onValueChange={
                                            (value) => {
                                                setSelectedSubject(value);
                                            }
                                        }>
                                            <SelectTrigger className="pl-10 w-full">
                                                <SelectValue placeholder={selectedSubject == "" ? "Subject" : selectedSubject} />
                                            </SelectTrigger>
                                            <ScrollArea className="max-h-[350px]">
                                                <SelectContent className="max-h-[350px]">
                                                    <SelectTitle>Core Subjects</SelectTitle>
                                                    <SelectItem value="Math">Math</SelectItem>
                                                    <SelectItem value="Science">Science</SelectItem>
                                                    <SelectItem value="History">History</SelectItem>
                                                    <SelectItem value="Language Arts">Language Arts</SelectItem>
                                                    <SelectItem value="Social Studies">Social Studies</SelectItem>
                                                    <SelectItem value="Physical Education">Physical Education</SelectItem>
                                                    <SelectItem value="Health Education">Health Education</SelectItem>
                                                    <SelectItem value="Core Subjects">Core Subjects</SelectItem>

                                                    {/** */}
                                                    <SelectTitle>World Language</SelectTitle>
                                                    <SelectItem value="English">English</SelectItem>
                                                    <SelectItem value="Spanish">Spanish</SelectItem>
                                                    <SelectItem value="Mandarin">Mandarin</SelectItem>
                                                    <SelectItem value="Hindi">Hindi</SelectItem>
                                                    <SelectItem value="Arabic">Arabic</SelectItem>
                                                    <SelectItem value="Portuguese">Portuguese</SelectItem>
                                                    <SelectItem value="Bengali">Bengali</SelectItem>
                                                    <SelectItem value="Russian">Russian</SelectItem>
                                                    <SelectItem value="Japanese">Japanese</SelectItem>
                                                    <SelectItem value="Punjabi">Punjabi</SelectItem>
                                                    <SelectItem value="German">German</SelectItem>
                                                    <SelectItem value="French">French</SelectItem>
                                                    <SelectItem value="Italian">Italian</SelectItem>
                                                    <SelectItem value="Korean">Korean</SelectItem>
                                                    <SelectItem value="Vietnamese">Vietnamese</SelectItem>
                                                    <SelectItem value="Turkish">Turkish</SelectItem>
                                                    <SelectItem value="Urdu">Urdu</SelectItem>
                                                    <SelectItem value="Javanese">Javanese</SelectItem>
                                                    <SelectItem value="Telugu">Telugu</SelectItem>
                                                    <SelectItem value="Marathi">Marathi</SelectItem>
                                                    <SelectItem value="Latin">Latin</SelectItem>
                                                    <SelectItem value="World Language">World Language</SelectItem>
                                                    {/** */}
                                                    <SelectTitle>Computer Science</SelectTitle>
                                                    <SelectItem value="Computer Science">Computer Science</SelectItem>
                                                    <SelectItem value="Algorithms">Algorithms</SelectItem>
                                                    <SelectItem value="Data Structures">Data Structures</SelectItem>
                                                    <SelectItem value="Operating Systems">Operating Systems</SelectItem>
                                                    <SelectItem value="Computer Networks">Computer Networks</SelectItem>
                                                    <SelectItem value="Databases">Databases</SelectItem>
                                                    <SelectItem value="Software Engineering">Software Engineering</SelectItem>
                                                    <SelectItem value="Artificial Intelligence">Artificial Intelligence</SelectItem>
                                                    <SelectItem value="Machine Learning">Machine Learning</SelectItem>
                                                    <SelectItem value="Cybersecurity">Cybersecurity</SelectItem>
                                                    <SelectItem value="Programming Languages">Programming Languages</SelectItem>
                                                    <SelectItem value="Computer Architecture">Computer Architecture</SelectItem>
                                                    <SelectItem value="Web Development">Web Development</SelectItem>
                                                    <SelectItem value="Mobile Application Development">Mobile Application Development</SelectItem>
                                                    <SelectItem value="Cloud Computing">Cloud Computing</SelectItem>
                                                    <SelectItem value="Computer Graphics">Computer Graphics</SelectItem>
                                                    <SelectItem value="Cryptography">Cryptography</SelectItem>
                                                    <SelectItem value="Quantum Computing">Quantum Computing</SelectItem>
                                                    <SelectItem value="Augmented Reality">Augmented Reality</SelectItem>
                                                    <SelectItem value="Virtual Reality">Virtual Reality</SelectItem>
                                                    {/** */}
                                                    <SelectTitle>Math</SelectTitle>
                                                    <SelectItem value="Addition">Addition</SelectItem>
                                                    <SelectItem value="Subtraction">Subtraction</SelectItem>
                                                    <SelectItem value="Division">Division</SelectItem>
                                                    <SelectItem value="Multiplication">Multiplication</SelectItem>
                                                    <SelectItem value="Algebra">Algebra</SelectItem>
                                                    <SelectItem value="Geometry">Geometry</SelectItem>
                                                    <SelectItem value="Trigonometry">Trigonometry</SelectItem>
                                                    <SelectItem value="Calculus">Calculus</SelectItem>
                                                    <SelectItem value="Linear Algebra">Linear Algebra</SelectItem>
                                                    <SelectItem value="Statistics">Statistics</SelectItem>
                                                    {/** */}
                                                    <SelectTitle>Sports</SelectTitle>
                                                    <SelectItem value="Soccer">Soccer</SelectItem>
                                                    <SelectItem value="Basketball">Basketball</SelectItem>
                                                    <SelectItem value="Baseball">Baseball</SelectItem>
                                                    <SelectItem value="Tennis">Tennis</SelectItem>
                                                    <SelectItem value="Football">Football</SelectItem>
                                                    <SelectItem value="Hockey">Hockey</SelectItem>
                                                    <SelectItem value="Volleyball">Volleyball</SelectItem>
                                                    <SelectItem value="Swimming">Swimming</SelectItem>
                                                    <SelectItem value="Track and Field">Track and Field</SelectItem>
                                                    <SelectItem value="Gymnastics">Gymnastics</SelectItem>
                                                    <SelectItem value="Golf">Golf</SelectItem>
                                                    <SelectItem value="Cricket">Cricket</SelectItem>
                                                    <SelectItem value="Rugby">Rugby</SelectItem>
                                                    <SelectItem value="Wrestling">Wrestling</SelectItem>
                                                    <SelectItem value="Boxing">Boxing</SelectItem>
                                                    <SelectItem value="Badminton">Badminton</SelectItem>
                                                    <SelectItem value="Table Tennis">Table Tennis</SelectItem>
                                                    <SelectItem value="Martial Arts">Martial Arts</SelectItem>
                                                    <SelectItem value="Cycling">Cycling</SelectItem>
                                                    <SelectItem value="Surfing">Surfing</SelectItem>
                                                    <SelectItem value="Skiing">Skiing</SelectItem>
                                                    <SelectItem value="Snowboarding">Snowboarding</SelectItem>

                                                </SelectContent>
                                            </ScrollArea>
                                        </Select>
                                    </div>
                                    <div className="relative w-full">
                                        <Target className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                                        <Input
                                            type="search"
                                            placeholder="Title"
                                            value={input}
                                            onChange={(e) => setInput(e.target.value)}
                                            className="w-full rounded-lg bg-background pl-8 pr-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent"
                                        />

                                    </div>
                                </div>

                            </AccordionContent>
                        </AccordionItem>
                    </Accordion>
                </DialogHeader>
                <ScrollArea className="max-h-[50vh] lg:max-h-[55vh]">
                    <ActualGallery searchQuery={searchQuery} selectedSubject={selectedSubject} input={input} />
                </ScrollArea>
            </DialogContent>
        </Dialog>
    </>
}

function SelectTitle(
    {
        children
    }: {
        children: any
    }
) {
    return <>
        <h1 className="ml-3 text-sm text-gray-900 my-2 font-semibold">{children}</h1>
    </>
}